#!/usr/bin/env bash

RESOLUTION=$(xrandr | grep "*" | awk '{ print $1 }')
LAPTOP="1366x768"
#DESKTOP=""

if [ "$RESOLUTION" = "$LAPTOP" ]; then
  sleep 3 && \
    st -g 85x19+33+52 &
  sleep 2.5 && \
    st -g 85x17+37-44 &
  sleep 2 && \
    st -g 76x37-16-44 -e tmux &

else
  sleep 3 && \
    st -g 231x17+32+52 -e tmux & # top
  sleep 2.5 && \
    st -g 93x19+32+373 & # bottom-left
  sleep 2 && \
    st -g 93x18+32-18 & # bottom-left
  sleep 1 && \
    st -g 136x38-35-17 & # bottom-right
fi
